/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benz_fastblur_Fast2Blur */

#ifndef _Included_com_benz_fastblur_Fast2Blur
#define _Included_com_benz_fastblur_Fast2Blur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benz_fastblur_Fast2Blur
 * Method:    buildBlur
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_benz_fastblur_Fast2Blur_buildBlur
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
